<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <name>oap-storage-cloud-ftp</name>
    <artifactId>oap-storage-cloud-ftp</artifactId>

    <parent>
        <groupId>oap</groupId>
        <artifactId>oap-storage-parent</artifactId>
        <version>${oap.project.version}</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>oap</groupId>
            <artifactId>oap-storage-cloud</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-net</groupId>
            <artifactId>commons-net</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
            <version>2.12.1</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>
</project>
